const List<Map<String, dynamic>> animalData = [
  {
    "id": "1",
    "name": "Luna",
    "breed": "Calico",
    "age": 3,
    "imageUrl": "",
    "type": "cat",
  },
  {
    "id": "2",
    "name": "Ted",
    "breed": "Gato Naranjo",
    "age": 2,
    "imageUrl": "",
    "type": "cat",
  },
  {
    "id": "3",
    "name": "Uyuyui",
    "breed": "Guacamayo",
    "age": 2,
    "imageUrl": "",
    "type": "bird",
  },
  {
    "id": "4",
    "name": "Coco",
    "breed": "Pejelagarto",
    "age": 1,
    "imageUrl": "",
    "type": "reptile",
  },
  {
    "id": "5",
    "name": "Cachupin",
    "breed": "Kiltro Shileno",
    "age": 1,
    "imageUrl": "",
    "type": "dog",
  },
  {
    "id": "6",
    "name": "Cala",
    "breed": "Galgo",
    "age": 4,
    "imageUrl": "",
    "type": "dog",
  },
];
